name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4.2.0

      - uses: jdx/mise-action@v2.1.0
        with:
          # only install node
          install_args: node
          cache: false
          log_level: trace

      - run: echo "$PATH"

      - run: cat "$GITHUB_PATH"

      - run: rm -rf ~/.local/share/mise/shims

      - run: sudo rm $(which npm)

      - run: which node
        continue-on-error: true

      - run: which npm
        continue-on-error: true

      # hangs because npm:@biomejs/biome is missing
      - run: mise x -- node --version
